wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.2.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704279650.425667
    t:
      1:
      - 1
      - 5
      - 11
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 53
      - 55
      3:
      - 23
      4: 3.9.18
      5: 0.16.1
      6: 4.2.1
      8:
      - 5
      13: linux-x86_64
